management:
#  server:
#    port: 9292 # actuator ?? ???? ??
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full # ? ??? ?? ??
#      mode: simple # ???? ?? ??
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always # ???? ?? ??
  #      show-details: always # ??? ?? ??
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/manage" # actuator ????? ?? ?? ??

info: # management.info.env ??
  app:
    name: ActuatorApplication
    author: yh, jl

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true  # 톰캣의 최대 쓰레드, 사용 쓰레드 수를 포함한 다양한 메트릭 확인
